// <auto-generated />
namespace BrainStation23TestProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class BaseModel_Added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BaseModel_Added));
        
        string IMigrationMetadata.Id
        {
            get { return "202009260827123_BaseModel_Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
